# -*- coding: utf-8 -*-
"""Copy of Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FWfE94g8KC0Al8dU-RpjdVU09LwegIs8
"""

#python -> Spark, Synapse Spark Pools-> PySpark or Scala

# EASY to write
# why?-> easy to read, simple syntax
# why not?-> SPEED and performance-> 72 times slower than C++/C#, 15-20 times slower than Java

# Pipelines-> small amount of instructions with isolation ,
 # transforming the data -> correction and ease is more important than VOLUME
 # PARALLEL processing

# python-> precompiled C++
# Datasets -> read/writing, stats, tansforming, visualize 
# Application program interface-> REST-> GET/POST/PUT/DEL 
# Machine Learning-> try

#OBJECT ORIENTED

# class-> special functions-> initialize the constructors and main function of C/C++ running behind the scenes
# INDENTATION-> spaces, tabs-> misplacing them will result in compilation error

def banana(val1,val2):
  return val1+val2

banana(1,2)

banana("hello","world")

banana("hello", 3)
#

fl = open('blah.txt', 'wt') # r/w/a , text mode or binary mode
fl.write(banana("hello","world"))
fl.close()

